POST http://localhost:3000/users
Content-Type: application/json

{
  "name" : "Maggie",
  "email" : "MAC@gmail.com",
  "password" : "password",
  "password_confirmation" : "password"
}

### create session - LOGIN

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email" : "TLC@yahoo.com",
  "password" : "password"
}

### all users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwOTY5NDd9.lf_hagMj0fwIvI6Z5xdfDbi-eAsKQyrkm2qrwL-efa0